name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository klonen
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Abhängigkeiten für das Frontend installieren
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: |
          npm install

      # 3. Abhängigkeiten für das Backend installieren
      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          npm install

      # 6. Deployment, falls alle Tests erfolgreich sind
      - name: Deploy to Uberspace
        continue-on-error: false
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # SSH-Setup: Erstelle .ssh-Verzeichnis und füge den privaten Schlüssel hinzu
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Sicherstellen, dass der richtige Host zum "known_hosts" hinzugefügt wird
          ssh-keyscan -H delphinus.uberspace.de >> ~/.ssh/known_hosts

          # Remote-Befehle für das Backend und Frontend ausführen
          ssh -v -o IdentitiesOnly=yes -i ~/.ssh/id_rsa kasmash1@delphinus.uberspace.de "
            cd /home/kasmash1/smashracqurt/ &&
            git pull &&
            cd frontend &&
            npm install &&
            cd ../backend &&
            npm install &&
            cd .. && cd .. &&
            supervisorctl restart backend &&
            supervisorctl restart frontend &&
            cd ../frontend &&
            npx cypress run &&  # Führe Cypress-Tests nach Neustart aus
            cd ../backend &&
            npx cypress run
          "      